basic/code10.s, basic/code2.s, basic/code3.s
The X16 additional BASIC statements start at token offset $80, and until https://github.com/X16Community/x16-rom/pull/6 which moved functions to start at offset $C0, the functions immediately followed statements.  This broke PRG compatibility of saved BASIC programs between emulator versions any time statements were added as it shifted the tokens of functions upwards.  This was addressed by https://github.com/X16Community/x16-rom/pull/6  
As we've added more BASIC statements, I fear the number of unallocated statement tokens is pretty small by comparison to the available function tokens.
Moving the start of functions from $C0 to $D0 seems prudent at this stage to ensure PRG compatibility for BASIC programs from R42 onward while giving us plenty of headroom for additional BASIC statements …
=> [BASIC] Move token offset for BASIC functions to $D0 to increase available unallocated statement tokens

basic/code2.s, basic/code3.s, basic/token2.s
`reslst2` is a table of the new X16 reserved words for the command parser.  We were at the cusp of the 256 byte index offset limit for this table before a contributor attempted to add a single BASIC command which ended up deadlocking the BASIC interpreter as the final "0" could never be reached in an 8-bit index register.
The changes add an additional reserved words table `reslst3` and additional code to check it.  It also adds a linker `.assert` to ensure the former table does not ever grow beyond 255 bytes
=> [BASIC] add tertiary reserved words table

Makefile, cfg/charset-x16.cfgtpl, cfg/dos-x16.cfgtpl, cfg/keymap-x16.cfgtpl, cfg/x16.cfginc, charset/vectors.s, codex/inc/x16_kernal.inc, codex/src/kernsup_cx.s, dos/main.s, graphics/jmptbl.s, inc/banks.inc, kernal/cbm/nmi.s, kernal/drivers/x16/memory.s, kernsup/kernsup_audio.s, kernsup/kernsup_basic.s, kernsup/kernsup_monitor.s, keymap/vectors.s
Prior to this commit, not every ROM bank had 6502 vectors installed.  This PR includes IRQ and NMI support in all banks.
In addition, David Murray has expressed a desire for NMI behavior to match the C64's STOP+RESTORE behavior.  Barring repeating the trampoline verbatim in every bank at the same addresses, doing this reliably requires a RAM-based trampoline.  There were 9-free bytes at the end of `KERNRAM2` and this new trampoline takes all 9 of them.
The trampoline, to allow for custom NMI handlers that return to the caller, preserve the A register and the previous ROM bank on the stack before setting the ROM bank to 0 and jumping indirect through (nminv).
In the default case, this does a warm reset by re-initializing I/O devices, restoring the KERNAL vectors, and eventually jumping …
=> [KERNAL] Add RAM NMI trampoline, add NMI vectors to every bank

kernal/drivers/x16/x16.s
The original routine dirtied $02-$21 shortly after it was just explicitly zeroed.
The new way is more characteristic of what the rest of the KERNAL does for cross-bank fetches, uses kernal ZP, and is more compact.
=> [KERNAL] tighten cartridge detection/boot routine

kernal/cbm/editor.s, kernal/drivers/x16/screen.s
This PR fixes bugs related to 20 column modes in two places
1) screen.s: for putting or fetching characters and/or colors from VERA memory, the logical column can be up to 80 characters.  The previous code calculated addresses correctly for 40 and 80 column modes by subtracting the screen width from the virtual column to find the physical column (and added a row) if we were in 40 column mode and we were at column 40 or above. For 20 column modes, we need a more complex process to calculate the VERA address, as this virtual column can live on any one of four rows if we allow for the current limit of 80 virtual columns.
2) editor.s: Now that a virtual line can span up to 4 rows (instead of 2), the check for EOL can overflow in 80 column mode and spuriously test true for non-EOL cursor …
=> [KERNAL] Handle line wrap correctly in 20 column modes

dos/fat32/fat32.s
This is likely not the final fix, nor the most elegant, but it does prevent the user from renaming a file into oblivion.
Closes #17
=> [DOS] Prevent cross-directory renames

kernal/cbm/channel/load.s
Unlike the upstream C64 source (verified by its disassembly), both variants of ACPTR on the X16 (both serial and VERA/sd card) zero the status byte unconditionally at the beginning of the function.  This breaks the expectation of the original VERIFY behavior which used the status byte to accumulate errors.
The easiest workaround seems to be to abort the verify at the first difference and report failure, otherwise the verify operation would only return failure if the final byte of the file and the final byte in memory had a mismatch.
Closes #15
=> [KERNAL] Abort VERIFY operation at the first error.

.github/workflows/build.yml, basic/init.s, basic/x16additions.s, kernal/cbm/editor.s, kernal/cbm/init.s, kernal/drivers/x16/rtc.s, kernal/drivers/x16/screen.s
At David's request, I'm adding support for an at-boot configuration of screen mode, which repurposes the 40/80 key (Scroll Lock) to toggle between these two configured modes.
The feature uses the first 22 bytes of the 64 available nvram bytes in the RTC at these offsets.
```
$00 = Default mode at boot (0/1)
$01/$0B = Screen Mode (SCREEN n) default = $00/$03
$02/$0C = $9F29 (DCSEL=0)        default = $21/$21
$03/$0D = $9F2A (DCSEL=0)        default = $80/$40
$04/$0E = $9F2B (DCSEL=0)        default = $80/$40
$05/$0F = $9F2C (DCSEL=0)        default = $00/$00
$06/$10 = $9F29 (DCSEL=1)        default = $00/$00
$07/$11 = $9F2A (DCSEL=1)        default = $A0/$A0
$08/$12 = $9F2B (DCSEL=1)        default = $00/$00
$09/$13 = $9F2C (DCSEL=1)        default = $F0/$F0
$0A/$14 = bbbbffff (b = …
```
=> [KERNAL] support nvram storage of screen mode configuration

basic/code17.s, basic/code26.s, basic/init.s, basic/x16additions.s, cfg/basic-x16.cfgtpl, cfg/x16.cfginc
There's a potential usability issue in the old behavior where default of `BANK 0` applied to both the ROM and RAM banks. You would ordinarily want the ROM bank to be in 0 or 4 when doing SYS calls, but before the BANK command was added, BASIC could only run SYS in ROM bank 4.  Thankfully the KERNAL jump table also already existed in ROM bank 4.
Unfortunately, the former behavior of the default RAM bank being 1 was no longer in effect after the `BANK` statement code was added.  This led people's programs that assumed RAM bank 1 was active at boot to clobber internal KERNAL variables if they used banked RAM in BASIC.
I think restoring the old default bank behavior prior to the introduction of the BANK command is the most needed part of this change, but for this to be possible, we need to be …
=> [BASIC] allow BANK statement to set RAM and ROM banks separately

kernal/cbm/nmi.s
Reaching warm start through NMI and reaching the monitor through BRK would always reset the screen mode to 0 and output device to VGA.  This change uses the profile from nvram instead.
=> [KERNAL] initialize screen with default nvram profile for basic warm start and monitor

basic/code16.s
In CBM BASIC 7, `ASC("")` returns 0.  This PR allows X16 BASIC to do the same, and avoid the need for error-checking `GET#` from a binary file.
Closes #28
=> [BASIC] Incorporate BASIC 7-like behavior for ASC()

kernal/drivers/x16/joystick.s
Some SNES controllers, such as SNES mouse, has bits 16-23 for other data and cannot be used to detect a presence. This could lead to incorrect detection for apps that only expect these bits to be equal to 0 to be present as Kernal documented.
=> [KERNAL] Properly set presence in certain SNES controllers

basic/code2.s, basic/code4.s
Are you sure this is BASIC 2? Because this doesn't behave like BASIC 2 ;)
`RESTORE <n>` moves the `DATA` pointer to first `DATA` statement at or following line number `<n>`   `RESTORE` without a parameter retains the BASIC 2 behavior of resetting it to the first `DATA` statement.
=> [BASIC] add optional line number for RESTORE statement

basic/token2.s, basic/tokens.s, basic/x16additions.s, dos/README.md, dos/file.s, inc/kernal.inc, kernal/cbm/channel/channel.s, kernal/cbm/channel/save.s, kernal/vectors.s, kernsup/kernsup.inc
The new I2C* keywords are generic for the entire I2C bus, not just for the SMC. The microcontroller address is $42
I'm leaving RESET as is, just jumps through the reset vector,
adds REBOOT as equivalent to the reset button push
adds POWEROFF which does work on both hardware and emu
adds the SLEEP command, parameter is in jiffies.  SLEEP without an argument is the same as SLEEP 0, which waits for until the next interrupt.  Rephrased, it will sleep this many whole jiffies plus a partial one.
Closes #36
=> [BASIC] add REBOOT, POWEROFF, SLEEP, I2CPOKE, I2CPEEK, and BSAVE

basic/x16additions.s
The BASIC `KEYMAP` routine treats the string parameter with a length > 5 as invalid, even though we have layouts that exceed this length.  Upped the max length to 9.
Closes #39
=> [BASIC] inappropriate string length checking for KEYMAP's argument

basic/x16additions.s, kernal/drivers/x16/screen.s
=> [KERNAL/BASIC] use default color value when unable to read nvram for it

Makefile, basic/init.s, cfg/kernal-x16.cfgtpl, kernal/signature.s
Up until this point, it has been difficult to determine what era, revision, or capabilities a ROM build has.  This is an attempt at solving that.  It creates a programmatically readable signature at the beginning of ROM bank 0.  16 bytes have been reserved for this purpose.
It currently contains the short git hash (8 hex digits), with a + if the repo has diverged from the commit.  This string is also in the BASIC banner.
More dependency fixes are needed in the Makefile, but this is a start.
=> [BUILD] add git signature

basic/code26.s, basic/x16additions.s
When using SAVE in BASIC direct mode, we should immediately return the error or lack thereof to the user.  This is a compromise between those who are frustrated with the lack of apparent feedback and for others, including David, who want CMDR-DOS to maintain the 1541-like behaviors.  This clears the drive error status implicitly.
This new behavior does not happen if `SAVE` is used within a program, as rare as that might be, so that the user can still check programmatically for error status. It only affects direct mode.
=> [BASIC] Provide feedback for SAVE in direct mode

kernal/cbm/irq.s
Later generations of X16 may act on the assertion of the VPB pin on the 65C02 by resetting the ROM bank latches to 0 before the processor reads the vector table.  This would enter KERNAL IRQ in ROM bank 0 while the zeropage address $01 still contains the bank that was active before the IRQ.
This code change supports that possibility by checking whether ZP $01 contains a value other than 0, and if so, runs the banked IRQ routine, so that the return goes to the previously active bank.
This adds 6 clock cycles to the beginning of a B0 IRQ and 18 clocks to a nonzero-bank IRQ on such future potential hardware.  It also adds 6 clocks to a nonzero-bank IRQ on current hardware without vector pull.
=> [KERNAL] support hardware vector pull in B0 IRQ vector

kernal/cbm/editor.s
This changes the f-key assignments slightly:
F2=`SAVE "`
F3=`LOAD "` (note the space and quote. This lets you load directly from a file listing.)
F5=`RUN`
F6=`MONITOR`
This is more consistent with other programs' use of these keys. Also so LOAD<cr> doesn't wipe out programs in progress. (Also, I'm tired of losing work because I tap F5 when I meant to tap F4.)
Previously, F5 LOADed with a CR, which wiped out the current BASIC program. This change fixes that. It also puts the F-keys in more consistent positions for those of us used to 80s era text editors.
=> f-key reorg

basic/x16additions.s, monitor/io.s
The BASIC `DOS` command and the `clear_status` routine would not handle errors not terminated by a CR.  The 1541 omits the CR in its channel 15 error strings.
This solves the freeze at boot with an IEC drive attached as device 8
=> [BASIC] handle 1541-style null-terminated errors

kernal/cbm/editor.s, kernal/drivers/x16/screen.s
This change adds modes 7-11 which include borders.  These modes are meant for CRT displays, have a defined border size, and avoid non-power-of-two scaling.
This discussion came up today with Adrian Black testing various modes on his CRTs, and finding that nearest neighbor vertical scaling (VSCALE something other than a power of two) on a CRT doesn't look good.
Native modes that can easily be reached from BASIC seem like the right answer.
=> [KERNAL] add new bordered screen modes

Makefile
This change causes builds against dirty git repos to replace the last character of the hash with a + instead of appending a +.  This makes the signature fixed at 8 bytes.
=> [BUILD] signature should always be 8 bytes

kernal/cbm/editor.s, kernal/drivers/x16/screen.s
This has no effect on VGA, but will have an effect on RGB/NTSC
Closes #62
=> [KERNAL] set interlace bit on mode change based on scale

Makefile, basic/token2.s, basic/tokens.s, basic/x16additions.s, cfg/util-x16.cfgtpl, inc/banks.inc, kernal/cbm/editor.s, kernal/drivers/x16/ps2kbd.s, kernal/drivers/x16/rtc.s, kernal/drivers/x16/screen.s, kernsup/kernsup_util.s, util/control.s, util/main.s, util/menu.s
This change includes the following:
[UTIL]
* New bank for utility routines.
* Ported David's CONTROL program (screen preferences utility) to work from ROM
* Added the new text screen modes
* Fleshed out time/date screen
* Minor visual fixes for 20 column modes
* Adds keyboard layout as a saved preference
* Preserves user memory, doesn't touch $02-$7F, $0400-$9EFF, or Banked RAM outside of bank 0
* Other programs, such as disk utilities are candidates for this bank.
[KERNAL]
* Moves the KERNAL's RTC NVRAM region to the last 32 bytes, and now claims and checksums that entire region
* Changes the layout of the NVRAM to allow for future expansion of the profiles without invalidating the checksum
* Honors keyboard layout as a saved preference in NVRAM
* Stealth enhancement of the get keymap …
=> [UTIL/KERNAL/BASIC] new UTIL bank, new BASIC MENU command, kernal changes to support new features

kernal/cbm/editor.s
`nxtd` molests the A register.  What comes out of that subroutine is A = the number of screen columns - 1.  The missing jmp didn't matter for what followed if it was a 20/40/80 column mode because 19/39/79 did not match any PETSCII compares that followed.  In fact, 19, is $13, which matches the Home petscii code already!  The other two are in the printable range and are not checked.
This also didn't break for 64 column modes because 63 was also in the printable range.
In 32 column mode, 31 (or $1f) matches the code for Blue, or color 6, which was then set after hitting HOME in 32-column mode.  This change avoids that behavior.
=> [KERNAL/EDITOR] add missing jmp after checking for HOME key which only caused a problem on 32 column modes

basic/code26.s, basic/x16additions.s
Enhance `DOS` command to return status of channel command if called from direct/immediate mode.
`curlin+1` == `$FF` is the condition for direct mode.  I was mistaken that I needed to check `curlin` for zero as well.   This caused checks for direct/immediate mode to fail after running a program.
=> [BASIC] Enhance DOS to display status after channel command, ensure similar behavior for SAVE command

kernal/drivers/x16/sprites.s
routine can address sprites 0-31 as well, so I updated that.
This makes the mouse routine not stomp on the layer bits (unless it was off), and leaves the flip bits untouched.
Closes #71
=> [KERNAL] make sprite_set_position more polite w/ attr byte 6

basic/basic.s, basic/code10.s, basic/code6.s, basic/x16additions.s, demo/test.s, dos/file.s, monitor/io.s, monitor/monitor.s
Particularly important for `ram_bank` and `rom_bank`.  A suspected timing violation on Proto 4 is causing the instruction  `st_ $0000` (absolute) to sometimes glitch to changing the ROM bank latch, depending on the address of the `st_` instruction.
=> [BASIC/DOS/MONITOR/DEMO] Cleaned up warnings re using absolute addressing for ZP locations

kernal/drivers/x16/joystick.s
This corrects the behavior introduced by b493150f975bf830e0abc68764adcc48176e9202
Closes #74
=> [KERNAL] fix joy detection assuming controllers were always connected

kernal/cbm/channel/errorhandler.s, kernal/cbm/editor.s, kernal/drivers/x16/ps2kbd.s
This change
* makes F2 suggest SAVE with overwrite
* doesn't press enter on F4 (SCREEN -1)
* removes keymap cycling using F9.  Use `MENU` and select a keymap from the control panel instead
* pressing 40/80 (scroll lock) while in a keyboard BASIN routine no longer assumes we're in BASIC and prints "READY.".  It checks the stack for the calling bank. If it's 4, then it prints "READY." otherwise it prints nothing.  This is still not perfect because hitting 40/80 during a BASIC `INPUT` will still print `READY.`  It might be worth removing this guesswork and never printing anything.
* remove part of a comment in `nstop` which is likely of C64 origin, but does not have the indicated behavior on X16.
=> [KERNAL] change F2/F4 behavior, remove F9, remove assumption in editor that we are in BASIC, remove inaccurate comment

basic/declare.s, kernal/cbm/channel/channel.s, kernal/cbm/editor.s, kernal/declare.s, kernal/drivers/x16/screen.s
PR opened at cc65 https://github.com/cc65/cc65/pull/2040 to update these constants to their R42 locations.
=> [KERNAL/BASIC] Add asserts in a best effort attempt to stablize locations used by cc65's RAM constants

monitor/monitor.s
I think I isolated the monitor init problem mention in issue #85 to address $2D (bank_flags).
This should be cleared on monitor startup.
=> Monitor init bug fix

Makefile
This seems to fix the build signature on MacOS by ensuring that the echo command is the binary in /bin rather than the shell builtin of whatever the current shell is.  This change also appears to work on our other supported build targets.  If we ever decide to target FreeBSD we might need a conditional here :)
Closes #86
=> [BUILD] avoid shell-builtin of echo command

graphics/drivers/framebuffer.s
This pull request fixes two bugs in fb_fill_pixels, which also reduces code size.
This also adds the feature of supporting arbitrary step sizes as parameter, increasing code size with either 60 or 93 bytes.
Arbitrary step size is requested here https://github.com/commanderx16/x16-rom/issues/100 . The original code also mentioned "TODO support other step sizes".
I am not familiar with how much space we can use for new features. Looking at the map file, however, it appears that DB5E to FFF9 (9.372 bytes) is available in bank 8. This is after adding the new features included here. Thus, it appears to me that we can afford some bytes for this feature.
Future improvements may be to look for all increments that can be accelerated by VERA (1,2,4,8,16,32,64,128,256,512,40,80,160,320,640), given …
=> Adjustments to fb_fill_pixels

basic/token2.s, basic/tokens.s, basic/x16additions.s
Along with `POINTER()` and `STRPTR()`, I believe these routines satisfy most of the deficiencies that led to @tomxp411's requests in #44 
Here's an interesting use for `LINPUT#` to parse out directory entries:
And here's a couple `BINPUT#` examples.  The file contains newlines (`$0A`) but no CRs (`$0D`), so they don't display, but the string is getting the bytes.
Closes #44
=> [BASIC] new keywords LINPUT, LINPUT#, and BINPUT#

basic/token2.s, basic/tokens.s, basic/x16additions.s
behaves like CHR$ but takes a second argument, a repeat count.
e.g.:
`?RPT$(33,10)` will print a string of ten exclamation marks.
=> [BASIC] add RPT$() function

.github/workflows/build.yml
Having a separate Release ROM image artifact will allow us to simplify automating builds for release x16emu, so that we no longer build the ROM in the emu CI.
=> [CI/CD] separate build for release ROM

basic/x16additions.s, util/control.s
This should be an actual fix for the return to BASIC from the menu command.  This no longer requires clearing the temporary use of the buffer since BASIC will now completely ignore it.  This also means the return from MENU will be to the READY prompt even if MENU were to be called from within a program.  This is probably the only sane behavior anyway since MENU borrows BASIC buffer space.
Control program now handles updating rtc clock to 24h mode if the time/date screen finds that it's in am/pm 12h mode.
=> [UTIL] refix return to basic, handle RTC 12h mode

kernal/cbm/editor.s, kernal/drivers/x16/screen.s
END now puts the cursor at the end of the line, Shift+END puts the cursor on the last row.
The cursor blink on used to be one frame after a key, now it's the same frame the key is processed.
DEL (not Backspace) will delete the character under the cursor. It does what a right cursor key would do, then processes it as if it were a backspace.
Closes #103 
Closes #104 
Closes #105
=> [EDITOR] (Shift+)END, DEL, cursor blink fixes

bannex/renumber.s
The renumber token parsing routine didn't take escaping into account, so it would apply to numbers following 5 other commands.
Closes #117
=> [BASIC] fix overbroad renumber parsing (FRAME, RECT, MOUSE, COLOR, PSGWAV)

kernal/drivers/x16/joystick.s
Some low-cost third party controllers on the market work on the SNES with the SNES' timing but do not work on the X16 which scans the controllers much faster. This change slows the SNES clocking (when run on an X16 running at 8MHz) to very nearly match that of the SNES.
Tested on a third party controller which did not work without this change.
=> Fix joystick scan timing to be more SNES-like

Makefile, charset/vectors.s, codex/src/kernsup_cx.s, dos/main.s, graphics/jmptbl.s, inc/banks.inc, kernal/cbm/irq.s, kernal/cbm/nmi.s, kernal/drivers/x16/memory.s, kernal/vectors.s, kernsup/kernsup_audio.s, kernsup/kernsup_bannex.s, kernsup/kernsup_basic.s, kernsup/kernsup_monitor.s, kernsup/kernsup_util.s, keymap/vectors.s
Since the hardware now resets ROM bank to 0 on interrupts. Putting vectors in every ROM banks isn't needed now. Also, to keep RAM handlers useful (users can put a custom low-latency handler here 😉), IRQ vectors in bank 0 now points directly to these handlers.
=> [KERNAL] Clean up IRQ and NMI vectors

audio/psg.s
There was some horrendously wrong logic here. This function has not been well-exercised until now.
Y was the volume value, not the PSG voice.  Let's reuse X for the voice, which is the register value / 4
=> [AUDIO] fix bad volume logic in psg_write

util/control.s
Does what it says in the header :-)
Tested on my hardware with the following procedure:
- PSU disconnected and backup battery removed for 5 minutes
- Backup battery reinstalled
- Computer booted, and control panel (MENU) started. I only changed the keyboard layout and stored that to NVRAM0 before exiting the control panel. The date/time was not set or started.
- PSU disconnected for 5 minutes (battery still installed)
- Booted the computer again. Keyboard layout fetched successfully from NVRAM.
=> Always enable VBATEN on exit from control panel

bannex/basic-declare.s, bannex/splash.s, basic/code14.s, basic/code2.s, basic/code26.s, basic/declare.s, basic/token2.s, basic/tokens.s, basic/x16additions.s, kernal/cbm/memory.s
In order to make it easier to withdraw memory from being available to BASIC, enhance the clear routine (CLR, RUN, etc) to reread the values from the kernal.
This also adds the BANNER command.  There'll be another PR later on that enhances the AUTOBOOT.X16 saved from the control panel to use it.
=> [BASIC] enhance BASIC to properly reread the top of memory from the kernal when it changes

basic/init.s
Fix for old Commodore BASIC bug mentioned on X16 forums from blog post https://c65gs.blogspot.com/2021/03/guest-post-from-bitshifter-fixing.html
=> fix old BASIC garbage collect bug

basic/x16additions.s
My first attempt at fixing this would leak memory on stack.
This fix ensures the stack pointer is reset in the same way as is done in the init2 function.
=> Prevent OLD from loading AUTOBOOT.X16

kernal/drivers/x16/screen.s
After looking at the Verilog, I see that DCSEL > 1 means DCSEL == 1.
This makes VERA 0.1.1 incompatible with FX register preserve/restore.
This (temporary) change excludes VERA < 0.3.x
=> [KERNAL] Handle VERA 0.1.1 incompatibility with FX preserve

audio/fm.s, audio/main.s, audio/memory.s, bannex/help.s, inc/audio.inc
This routine inside of `ym_init` inhibits IRQs, and sets Timer A and Timer B on the YM chip with values such that Timer B expires first on OPM and Timer A expires first on OPP, loads the timers while enabling IRQs, waits until the status byte shows a value, then saves that value.  If there is no functioning YM chip, the ym_write will likely fail on the busy flag timeout in `ym_write` or the 65536-iteration timeout will be exhausted.
At the end  of the section, the timer/IRQ flags are cleared and the previous state of the processor flags is restored.
Since `ym_init` is run in the KERNAL init routine, this detection is done at poweron.
`ym_get_chip_type` in the Audio API will return the detected chip type, which applications and music playback libraries can use to detect which chip is …
=> [AUDIO] add new YM variant detect routine (OPM/OPP)

Makefile, findsymbols, scripts/symbolize.sh
Some build system tweaks, especially for the benefit of BSD systems:
- bash is not always installed in /bin
- GNU make is not always called 'make'
=> [build] Portability enhancements

kernal/cbm/editor.s
This looks like a C64ism that is not needed.  It interferes with pasting in the emulator using Ctrl+V because the KERNAL can pick the Ctrl up as a delay, and would eat the complete keyboard buffer, losing pasted characters.
=> [KERNAL] don't clear the keyboard buffer after Ctrl delay on CHROUT scroll

kernal/drivers/x16/ps2mouse.s
This is the rest of the fix for https://github.com/X16Community/x16-emulator/issues/133 and also addresses an annoyance that @misterblack1 had mentioned where the mouse scaling was not separate for screen modes with non-square pixels.
=> [KERNAL] handle differing h/v mouse scaling based on screen mode

kernal/drivers/x16/ps2mouse.s
When deactivating the mouse in a large screen resolution and reactivating it in a lower resolution, the mouse pointer could activate while out of bounds.  Reset the pointer to the center of the screen to avoid this.
=> [KERNAL] set mouse pointer to center of screen when activating

graphics/graph/console.s
These variables were never initialized and bad behavior ensued when the emulator defaulted to randomized RAM.  The linked issue fails similarly on hardware before this change.
Closes #152
=> [GRAPH] initialize px/py in console_init

kernal/drivers/x16/beep.s
This bug was found today when someone had printed a Ctrl+G and then later tried to use the PSGPLAY command and got no sound out.
=> [KERNAL] avoid clobbering the pan (L+R) value in PSG voice 0 after beeping

dos/match.s
Characters in filenames that are incompatible with CMDR-DOS (including those not in ISO-8859-15) are replaced with `'?'`.  Add comma `','` to that list
=> [DOS] replace commas in FAT32 filenames with '?'

charset/iso-8859-15.s
This reverts its replacement inadvertently caused by #84
=> [CHARSET] restore butterfly glyph to primary ISO set

kernal/drivers/x16/memory.s, monitor/monitor.s
This makes the monitor substantially more useful upon a BRK instruction.
=> [MONITOR] populate stack frame so that monitor's view of the registers at BRK are correct

bannex/basic-declare.s, basic/code1.s, basic/code26.s, basic/declare.s, basic/init.s, basic/token2.s, basic/tokens.s, basic/x16additions.s
EXEC will take a memory location containing a series of BASIC immediate mode commands.  While EXEC is active, commands will be fed line by line as long as immediate/direct mode is active.  EXEC mode stops when
* it reads a null character ($00) from memory
* it reads a line that exceeds BASIC's max line length (80)
* the stop key is pressed
* basic is cold or warm started
This command can be used as part of an approach to get tokenized BASIC from plain text data.
This PR also augments `BLOAD` to feed the end load address into the X/Y SYS communication memory locations, so that BASIC programs can programmatically retrieve it.  This should help other cases of BLOAD where a BASIC program doesn't have foreknowledge of the exact sizes of the files to be loaded.
Here's a PoC for the EXEC command …
=> [BASIC] new EXEC command and support

Makefile, basic/token2.s, basic/tokens.s, basic/x16additions.s, kernal/drivers/x16/ps2mouse.s
Summary of changes.
Makefile:
- Imports Kernal variable wheels when building BASIC rom
BASIC:
- Adds command MW that returns the mouse wheel value
- MX, MY, and MB changed to preserve mouse wheel value
ps2mouse.s:
- The config function fetches mouse device ID, and stores it for later use by the mouse scan function
- If the mouse device ID = BAT_FAIL, no mouse is attached to the system, or the mouse init failed. In this case, the config exits without showing the mouse pointer
- The mouse scan function fetches a fourth movement packet byte if device ID is 3 or 4
- The mouse wheel movement is added to a signed 8 bit buffer ("wheel")
- The mouse get function returns the wheel value in X register. The wheel value is cleared at the same time.
- The mouse get function returns flags for extra …
=> Intellimouse support

basic/x16additions.s, monitor/monitor.s
This PR has several fixes/enhancements
* New `J` command, JSR from monitor
* RTS from `G` command returns to the point from which MONITOR was called
* PC upon entry to monitor was 2 off
* fixed stack setup in the case of calling monitor explicitly from a bank other than BASIC
=> [MONITOR] add J command, fix stack problems with G command, RTS from G fix

Makefile, bannex/basic_far.s, bannex/dos.s, bannex/main.s, basic/code1.s, basic/code26.s, basic/declare.s, basic/x16additions.s, inc/bannex.inc
This PR implements most of the DOS wedge shortcuts, but directly into the immediate mode interpreter loop rather than as a `chrget` replacement.
| Command | Action |
|-|-|
| `/<filename>` | Load a BASIC program into RAM |
| `%<filename>` | Load a machine language program into RAM (like `,8,1`) |
| `↑<filename>` | Load a BASIC program into RAM and then unconditionally run it |
| `←<filename>` | Save a BASIC program to disk |
| `@` | Display (and clear) the disk drive status |
| `@$` | Display the disk directory without overwriting the BASIC program in memory |
| `@#<device number>` | Change default DOS device |
| `@<command>` | Execute a disk drive command (e.g. `S0:<filename>`, `CD:<dir>`) |
Any `@` command will also work as a `>` command.
This implementation does not honor `@Q` …
=> [BASIC/BANNEX] emulate DOS wedge commands

Makefile, monitor/monitor.s
As discussed in #134 we want to avoid stomping on user ZP.  There are enough scratch ZP locations that belong to BASIC that we can use while the monitor is running, so instead of preserving any ZP, we can simply take over those locations.
This PR also creates a new command `K` which changes the RAM bank, and can also be used to set VRAM/I2C modes. the old `O` command is now for changing only the ROM bank.
Other cleanup done as well.
Closes #111
=> [MONITOR] move ZP usage to BASIC area, honor RAM bank separately from ROM bank, enhance register dump/read

dos/declare.s, dos/main.s
after the FAT32/DOS split, some variables owned by DOS were no longer being initialized.
=> [DOS] init code missed these variables after they had moved

Makefile, bannex/main.s, bannex/x16edit.s, basic/token2.s, basic/tokens.s, basic/x16additions.s, inc/banks.inc, inc/bannex.inc
This PR implements the EDIT command.
The EDIT command may be invoked with no params or with a string param. In the first case, it opens X16EDIT with an empty new buffer. In the second case, it tries to open the specified file.
=> EDIT command

util/hexedit.s
This allows left to wrap to the previous line, and right to wrap to the next line.
=> [UTIL] improve hexedit left/right navigation

bannex/x16edit.s
This makes EDIT use the default device number provided by basic_fa.
If you select a device that is not present, this is correctly reported by the editor if an SD card image is attached.
But if the host file system is used, no error is raised.
=> Set default device number

README.md
I noticed the new build dependency but no instructions to obtain it, so I added some.  I haven't tested the Visual Studio 2017 or XCode builds on the lzsa repo, but I refer to them in this change.  I hope they work!
=> Add lzsa build instructions to README

util/menu.s
Emulator build problems with the unrecognized escape.
=> [UTIL] comment was breaking rom_lst.h support

basic/code26.s
If one ran
`10 LOAD "OTHERPROG.PRG"`
and the new program was written in BASIC and used variables, the new program would be corrupted.  This resolves this issue by properly setting vartab based on the load-end, even when not in immediate mode.
=> [BASIC] fix BASIC V2 bug not resetting variables pointer when chain-loading

basic/x16additions.s
The `size` memory location was getting clobbered by string garbage collection if it happened to run inside of `strspa`.  This works around that problem.
=> [BASIC] LINPUT(#)/BINPUT# fix spurious STRING TOO LONG after string GC

basic/code26.s
In previous versions, you could PEEK(0) immediately after a BLOAD, but it didn't reset the bank set by the `BANK` command.  This lack of durability was problematic.  Now the end bank after a LOAD/BLOAD is set as if it were via the BANK command.  It's still able to be PEEKed from memory location 0, but this value will now persist even if there are other statements in between the BLOAD and PEEK.
=> [BASIC] switch bank to BLOAD end

kernal/drivers/x16/joystick.s
The previous `trb` reset both latch and clock.  The changes afterwards caused only clock to be reset and then a few instructions later, latch got reset.  This restores the old behavior, simulating the `trb`, and joysticks in emu now work correctly.
Both R45 and this commit work on my hardware.
=> [KERNAL] joystick: restore older latch/clock release order

kernal/drivers/x16/joystick.s
R44 seems to have had better support for different types of controllers according to testimonies on Discord.
In R44 the latch period was 4.25 us, if I'm counting the cycles correctly:
```
tsb nes_data ; 0, I here assume that the latch is set when the instruction is finished
pha ; 3
pla ; 4
pha ; 3
pla ; 4
pha ; 3
pla ; 4
pha ; 3
pla ; 4
trb nes_data ; 6 => total 34 cycles = 4.25 us
```
In the current master this is a bit shorter, I think 4.00 us:
```
sta nes_data ; 0
pha ; 3
pla ; 4
pha ; 3
pla ; 4
pha ; 3
pla ; 4
pha ; 3
pla ; 4
stz nes_data ; 4 => total 32 cycles = 4.00 us
```
This PR adds another pha+pla, making the latch period 39 cycles=4.87 us.
=> Make joy latch as long as it was in R44

kernal/drivers/x16/ps2mouse.s
Guard mouse_get with SEI to prevent mouse data being changed by mouse_scan.
=> Prevent mouse_scan during mouse_get

graphics/drivers/framebuffer.s
Loops didn't verify if there was actually any remaining data left to copy. Hence copying 256 bytes more than asked for.  Fixes #217
=> Fix overflow in FB_get/set_pixels when lsb of amount is 0

bannex/dos.s
had to turn the first beq into a jmp because the offset became too large and ca65 doesn't do this automatically :|
=> Correctly set default drivenr from petscii chr too. Fixes #216

kernal/drivers/x16/joystick.s
Give slower controllers a few extra nanoseconds to respond to NES clock changes.
=> Add small delay before sampling controller data to fix #215

basic/code17.s, math/code25.s, math/jumptab.s, math/math.inc
It calls into the equivalent code that was already present in Basic in the val routine.
I am not familiar with ca65's import/export mechanism of symbols, so please have an extra look at that
[testprog.zip](https://github.com/X16Community/x16-rom/files/13494350/testprog.zip)
source code for the above test program:
```
%import textio
%import floats
%import string
%zeropage basicsafe
%option no_sysinit
main {
sub start() {
str buffer = "???????????????????????????"
repeat {
txt.print("enter number: ")
void txt.input_chars(buffer)
txt.print("\nprog8's parse_f: ")
float value = floats.parse_f(buffer)
floats.print_f(value)
; floats.VAL_1 is defined as:
; romsub $fe09 = VAL_1(uword string @XY, ubyte length @A) clobbers(A,X,Y) -> float @FAC1
txt.print("\nrom val_1: ")
value = floats.VAL_1(buffer, …
```
=> implement VAL_1 routine $fe09 of the FP library

kernal/cbm/nmi.s, kernal/drivers/x16/memory.s
Previously calling the `monitor()` kernal routine was a one way trip and exiting the monitor always returned you to a BASIC prompt.
Now it only does a basic warm start if the monitor was called from BASIC (or the BRK vector, apparently), and if not, it simply does an RTS to hand control flow back to the caller.
=> Monitor returns to caller at exit if not having to return to BASIC.

fat32/fat32.s
If you save a file prepending the file name with "@:" it will currently delete a directory having the same name.
I suppose this is bad, and that it will orphan all files in that directory.
The attached code prevents overwriting directories this way.
I'm not sure about the error number. There're not a lot of suitable error codes to choose from in dos/file.s. For now it returns FILE EXISTS when you try to overwrite a directory.
This is somewhat linked to issue #232.
=> Prevent file overwrite from deleting directories

util/control.s
Previously we didn't mask off the leap year bit returned in the month field when reading it.
=> [UTIL] fix setting month when a year is a leap year

basic/code1.s, basic/init.s
If OLD is run on a newly booted system, it will just hang.
This change allows OLD to run without hanging, it restores a random BASIC line, but it does not hang
=> Prevent OLD command from hanging when run without a program in memory

kernal/cbm/irq.s, kernal/drivers/x16/x16.s, kernal/open-roms/interrupts/ea7e.ack_cia1_return_from_interrupt.s, kernal/open-roms/open-roms.s
`irq_ack` is only called in `keys` and consists of a `lda` and a `sta` instruction, which take five cycles; by inlining the code, code execution time is reduced by 12 cycles (`jsr` + `rts`).
I've also replaced the call in open-roms; I don't know whether that's all that is necessary for open-roms, however, it doesn't even compile prior to my changes, so I cannot verify it.
=> Inline `irq_ack`

Makefile, codex/Makefile, fat32/fat32.s, inc/banks.inc, inc/mac.inc, kernal/cbm/channel/load.s, kernal/cbm/irq.s, kernal/drivers/generic/softclock_date.s, kernal/drivers/generic/softclock_time.s, kernal/vectors.s
The ROM isn't going to be used with a C64 anymore, and the ROM neither assembles nor works on a stock 6502 or 6510 anymore. This PR removes the leftover machinery.
=> [KERNAL/FAT32/CODEX] Remove support for non-65C02 CPUs and the C64

kernal/drivers/x16/rtc.s, kernal/ieee_switch.s
Opening a file would clobber r3H, and setting the DOW programmatically could have cleared the VBATEN bit
Closes #249
=> [KERNAL] fix two DOW bugs

cfg/kernal-x16.cfgtpl, kernal/drivers/x16/memory.s
The prior location of VARFONTS was covered by the $200-$3FF clearing, so we need to also clear it in B0.
=> [KERNAL] init VARFONTS in ramtas

basic/code17.s
On the code imported from the C64, the only function that mutates `poker` is `PEEK`, thus preserving `poker` inside of `PEEK` was effective in making `POKE` happy.  X16 additions mutate it in at least 3 more functions (VPEEK, STRPTR, POINTER), so moving the preserve to the `POKE` statement should fix this logic.
Also removed a misleading comment that is no longer relevant, since (B)LOAD also populates the SYS shadow registers now.
=> [BASIC] fix POKE writing to the wrong place if the value expression disturbs `poker`

diag/diag.s
While writing the documentation for the diagnostic ROM bank, I found that the error codes could be written in a better way and that the text used to tell that the base memory had completed initial test was not clear. This should fix those two issues and make Diagnostic ROM and documentation match.
=> Small update to diag ROM - Clarifying initial basemem test and error codes

cfg/diag-x16.cfgtpl
bank 16 (the final bank) was overrunning 16KB, which, while not a real issue while it's the final bank, was causing validation errors in x16-flash
=> [DIAG] fix memory region size so as not to overrun 16kB

cfg/audio-x16.cfgtpl, cfg/bannex-x16.cfgtpl, cfg/codex-x16.cfgtpl, cfg/diag-x16.cfgtpl, cfg/kernal-x16.cfgtpl, cfg/monitor-x16.cfgtpl, cfg/util-x16.cfgtpl, cfg/x16.cfginc, inc/banks.inc, inc/jsrfar.inc, kernal/drivers/x16/memory.s
The native RAM code is 2 bytes shorter due to the savings in size from stack-relative addressing, even with the added SEP/REP
=> [KERNAL] implement native-capable jsrfar

cfg/kernal-x16.cfgtpl, cfg/x16.cfginc, kernal/drivers/x16/ps2kbd.s
`tmp2` is in flux outside of `kbd_scan`, and it wasn't preserved by `kbd_scan`, so there was a potential race where `kbd_scan` in the ISR modified tmp2, corrupting state in the main part of the kernal if it happened to rely on the value of `tmp2`.
This change gives `kbd_scan` its own dedicated space for this temporary byte.
=> [KERNAL] use dedicated tmp memory location for kbd_scan

kernal/drivers/x16/screen.s
We have had the deprecation warning at boot for old VERAs for the last 9 months, it's probably okay to remove the check at this point.
After this change, this is what would likely happen on old VERAs:
* Unversioned = display will probably go blank once it reaches BASIC and the cursor starts blinking
* 0.1.1 - display will be offset to the right as it inadvertently sets HSTART to a high value, you can only see a small region.
Both situations can be recovered from via an AUTOBOOT.X16 that loads a flash tool.
=> [KERNAL] remove support for non-FX VERA versions

kernal/cbm/channel/errorhandler.s, kernal/cbm/channel/load.s
This patch prevents LOADing large files that run all the way through low RAM and into I/O space.  The LOAD is halted before actually touching $9F00.
Closes #243
=> [KERNAL] halt before clobbering I/O space when LOADing through $9EFF

cfg/kernal-x16.cfgtpl
As segments have expanded, they've tended to bump up against the fixed 65C816 support locations.  This arrangement should help a little bit w/ the rest of the immediate expansion needed.
=> [KERNAL] rearrange segment layout to better fit

inc/banks.inc
The need for permanence of the IRQ/NMI locations was before vector pull was wired to reset to bank 0, so it is no longer true.
Other cleanup.
=> [KERNAL] comment cleanup, remove unused macros

basic/x16additions.s
The `poker` preservation logic was moved out of `PEEK` and into `POKE` in #275 which solved the memory clobbering error when using `POINTER()` and `STRPTR()` inside expressions for `POKE`, but unfortunately it broke pointer expressions inside of `VPOKE`.
=> [BASIC] fix VPOKE pointer preservation

kernal/cbm/editor.s
The original C64 code did this
The `color` variable on C64 is limited to 0-15, so the location is always positive.  The original C64 source code was using `bpl` as an unconditional branch. The X16 uses the high nibble for the background color (or colors >= $80 in T256C mode), so this is no longer a good assumption.
In the course of X16 development, the branch became too far away, so the sense was inverted, but the logic was still incorrect.
Changed it to a `jmp` instead.
Closes #338
=> [KERNAL] fix old CBM porting bug which assumed color variable was 0-15 for unconditional branch

graphics/drivers/framebuffer.s
The ADDR0 is set to auto-increment by the cursor position set , so a read op is enough to increment the ADDR0 pointer (and is faster to boot)
Closes #340
=> [GRAPH] FB_set_8_pixels(_opaque) did not handle VRAM addresses > 0x0ffff

math/code19.s
The constant `addprc` is present in most Microsoft BASICs of the era from which this code was ported, and in other references this constant means "additional precision".  On the C64, and hence the X16, this constant was set to 1.
For the issue at hand, the X register was set to `#252`, and then incremented before the store of the first byte on (pre-diff) line 165, which set the index to 253, (or with ZP wraparound, -3) relative to `reslo`, which is `resho`, or the first byte of the FP result quintet.
The negative offset was a useful space and cycle saving measure as it allowed the code to skip a compare instruction after incrementing X, but allow a branch for 0 and then for 1.  Unfortunately, when attempting to use this in native mode on the 65C816, where the ZP wraparound behavior is …
=> [MATH] modify fdiv to support 65C816 native mode

kernal/x16/65c816/interrupt.s
This change causes the default native NMI indirect vector target to switch to emulation mode while setting up an RTI stack frame, giving an emulation NMI handler that is 65C816-unaware the ability to return back into native code.
Removed the explicit jump from one of the irq handling macros to make them more general so that the routine could be reused.
=> [KERNAL] 65C816 native NMI sets up for native return from emulated call

kernal/drivers/x16/x16.s
On the C64, `ioinit` disables interrupt sources entirely, until `cint` enables the default one.  After this change, the same thing now happens on the X16. 
Ultimately, this allows the default NMI and BRK handlers to successfully give control to the user (in BASIC or MONITOR) even when the interrupted program uses VIA timers, LINE interrupts, YM2151 IRQs, or other IRQ sources on VERA.
=> [KERNAL] ioinit now disables interrupt sources

kernal/cbm/editor.s, kernal/drivers/x16/ps2data.s, kernal/drivers/x16/ps2kbd.s
It's been reported in the SMC channel on Discord that some keyboards will not light up the Num Lock LED on boot if you have set keyboard typematic rate/delay in the MENU config. This at least happens with the official Perrix keyboard.
I don't have access to that keyboard to take any data samples, but the issue is likely caused by the Kernal sending the set typematic rate/delay command during keyboard POR or when the SMC is sending the set LEDs command.
The keyboard POR should according to IBM specs take minimum 150 ms and maximum 2.0 s. It might therefore differ a lot how long the POR takes.
To remove the risk that there is interference between the SMC keyboard init and the Kernal init, I suggest that we remove the set typematic rate/delay from Kernal init. We could move it to the …
=> Move typematic rate/delay setting from Kernal init

basic/code17.s
As the original NMOS 6502 didn't have `(zp)` addressing, it used `(zp),y` addressing with a constant .Y = 0 for ZP indirect loads. Not only is this not necessary anymore, as both our target CPUs support `(zp)` addressing, it leads to behavior differences when `POKE` is used on addresses in the IO page:  In the extra CPU cycle needed to calculate the target address during `sta (zp),y`, the 65C816 performs a read of an invalid address, while the 65C02 performs a read of what is presumed to be the last fetched instruction byte, causing an extra read from the IO page on the 65C816.
This PR replaces all unnecessary `(zp),y` usages in code17.s, where the implementation for `PEEK` and `POKE` lives.
=> [BASIC] Replace ldy #0 + (zp),y addressing with (zp) addressing

fat32/fat32.s
Bank area blockwise reads and writes which wrap RAM banks in the middle of the read or write operation formerly used indirect indexed mode in $9Fxx,y to continue the operation, where .Y would start with the offset to put the first byte at $A000. 
This change prevents that condition on the 65C816.
Backstory:
On the 65C816, when doing indexed reads and writes, the cycle immediately before the valid operation is a read of the indexed offset without carry.
For instance
```
ldy #$80
lda $9f80,y
```
For the `lda` instruction on the 65C816, just like on the original 6502, the CPU will first add .Y to the address without carry, and do a read cycle.  This will read from `$9f00`.  If the page wrapped, the CPU will do another cycle, and on this the carry of the wrap will be added to the effective …
=> [FAT32] Avoid indexed access with base in IO range on 65C816

kernal/cbm/editor.s, kernal/drivers/x16/ps2data.s, kernal/drivers/x16/ps2kbd.s, scripts/relist.py, scripts/trace_info.py
The code avoids calling the handler-unsafe routine `fetch_typematic_from_nvram` inside the ps2 fetch handler.
This also includes fixes for Python regexes in the relist build scripts.  String literals without the `r` prefix (raw string literal) could have the possibility of the escapes being processed before being passed to the `re` module.
=> [KERNAL] typematic preference apply fix, build relist fixes

Makefile, basic/graph.s, basic/token2.s, basic/tokens.s, cfg/graph.cfgtpl, graphics/graph/graph.s, graphics/math.s
This is a fast implementation of an extended Bresenham circle algorithm to draw ellipses, based on http://members.chello.at/~easyfilter/bresenham.html
It adds a fast 8x8 multiply routine, fast 16 bit squaring, and a traditional 16x32 shift and add multiply routine.
=> [GRAPH/BASIC] implement GRAPH_draw_oval and BASIC "OVAL" and "RING" commands

basic/code17.s, cfg/x16.cfginc
The following modifications in `basic/code17.s` fixes the 1E39 bug (see #247) that we inherited from the C64.
=> [BASIC] Fix 1E39 bug (Issue #247)

kernal/drivers/x16/ps2data.s, kernal/drivers/x16/ps2kbd.s
This change avoids an infinite spinlock when changing the LED state with no PS/2 keyboard attached.
=> [KERNAL] remove the infinite spinlock on setting the kbd LEDs and defer to next tick

fat32/fat32.s
When creating a new file, the start cluster in the directory entry is set to all zeroes.  However, the context's state is set up so that the first byte written to the file causes the driver to allocate a new cluster.
If no byte is written to the file, this is never changed.
Prior to this change, when opening an existing file, the start cluster was trusted to point to the sector that the file's data began on.  Unfortunately since this was the value $00000000, which is an alias for the root directory's start cluster, the next write would clobber the root directory and trash the SD card entirely.
Rather than unconditionally trusting that the file has data and opening the first cluster, we now handle the case correctly when the opened file's size is 0.
=> [FAT32] fix corruption when appending to empty file

bannex/dos.s
=> add a ':' after the RUN command in dos wedge for ^

kernal/drivers/x16/x16.s
While building and debugging cartridges, booting to the live system with the cartridge inserted is useful.
=> [KERNAL] add ability to bypass cartridge boot by holding Shift

cfg/kernal-x16.cfgtpl, kernal/cbm/util.s
PRIMM is the only KERNAL library function left that uses abs,x addressing for stack access, thereby not working with a 65C816 in native mode where the stack page might have been moved. This PR adds an implementation that uses the 65C816's stack-relative addressing to work with arbitrary stack pointers; it also optimizes the 65C02's code path.
=> [KERNAL] PRIMM: Add 65C816 native mode support and optimize the code

scripts/relist.py
Fixes an issue in the "lst_matcher" regex in relist.py. I noticed the generated rom_lst.h file didn't contain any listings for most of the banks, so I traced the problem to this issue in relist.py.
=> Fix "lst_matcher" regex in relist.py.

kernal/drivers/x16/entropy.s
=> improve entropy_get by including scanline as source

kernal/x16/extapi.s
This exposes a functionality that already was available to the internal kernal code. This function works in a similar manner to `memory_decompress`, but instead of taking an address of compressed data in `r0`, it takes, in `r4`, an address of a function that *streams* LZSA2 data byte by byte each call. 
This was already available in the kernal and such a function might be useful in many scenarios, such as:
- decompressing data incoming from a serial connection on the fly
- decompressing stuff stored on a cartridge ([usage attested in the kernal itself](https://github.com/X16Community/x16-rom/blob/8e9117eb864a6ffc66ced72f5bb168ee0b1cbf76/kernal/drivers/x16/ps2kbd.s#L200-L214))
- decompressing data from the banked ram (and automatically handle the bank switching, obviously)
I'll write the …
=> extapi: Add `memory_decompress_from_func`

kernal/memory.s
The old implementation first accumulated a whole number of 256 byte chunks.
Then, it did the remaining bytes.
The old implementation was incorrectly using Y as a downcounter AND an offset using the "lda (r0),y" instruction for the remainder part. Causing remainder bytes to be accumulated in the wrong order.
This pull request fixes the order of the remainder bytes, so that they get accumulated in the same order as the rest of the file.
For the record: r1L (number of bytes) gets trashed, since r1H also gets trashed. Although r0 (address) is preserved.
Fixes #381 
This change causes the function to generate the same results as "CRC-16/IBM-3740", ref this online calculator: https://www.crccalc.com/?crc=01%2002%2003%2004&method=CRC-16/IBM-3740&datatype=hex&outtype=hex
=> Fix crc function

kernal/cbm/channel/load.s
* The logic that switches to bytewise load just below $9F00 did not check for EOI, leading to an erroneous extra byte read after EOI in cases where:
* A load which only required a single MACPTR was started after $9D00.
* A longer load ends such that the pointer lands after $9D00 on the same MACPTR that reaches the file's end.
reported by tony3068 (Discord)
* The bytewise load check where it checks whether the load is VRAM only checked agains VERA "bank" 0 and erroneously triggered the $9F00 check when loading to VERA "bank" 1.   This was covered in #367 
Closes #367
=> [KERNAL] handle two LOAD edge cases

basic/code9.s
=> fix: correct value of BASIC π constant

dos/file.s, dos/functions.s, fat32/README.md, fat32/fat32.s
`fat32_read` and `fat32_write` currently use `krn_ptr1` to determine whether to increment
the buffer pointer or not; the latter is used for reads from / writes to an IO address.
As this is a DOS variable with a variable address that is unrelated to the other named
FAT32 variables, this commit changes this to use the carry flag instead; calling the function
with carry set prevents address incrementing.
=> [DOS/FAT32] Use carry for instead of `krn_ptr1` to indicate writes to the same address

fat32/fat32.s
=> [FAT32] Handle files >= 2GiB in block read funcs, cleanup conditionals meant for the obsolete C64 fork of KERNAL
