X16Community/x16-rom

- graphics/drivers/framebuffer.s
https://github.com/commanderx16/x16-rom/pull/362
> Implement fb setpalette

- kernal/drivers/x16/memory.s
https://github.com/commanderx16/x16-rom/pull/377
> Enable kernal to accurately detect amount of memory installed

- kernal/lzsa.s
https://github.com/commanderx16/x16-rom/pull/371
> Memory decompress to vram fix

- basic/code10.s
- basic/code2.s
- basic/code3.s
https://github.com/commanderx16/x16-rom/pull/374
> Future additions of BASIC statements and functions without breaking tokenized representation

- basic/basic.s
- basic/sound.s
- basic/token2.s
- basic/tokens.s
https://github.com/commanderx16/x16-rom/pull/378
> BASIC sound

- kernal/cbm/init.s
- kernal/drivers/x16/x16.s
Requested by David to support cartridge boot at power-on
> [KERNAL] ROM bank 32 cartridge boot support

- codex/src/edit.s
> Fix for delete line issue, crashing CODEX

- cfg/kernal-x16.cfgtpl
- cfg/x16.cfginc
- kernal/drivers/x16/memory.s
> [KERNAL] reserve a page of B0 for a user param passing API

- basic/init.s
> [BASIC] shorten splash screen version string for 40col displays

- basic/x16additions.s
> [BASIC] swap behaviors of REBOOT/RESET

- basic/init.s
This logic could be made more compact, for sure. I'll probably come back around to tighten this later.
> [BASIC] Use compact splash banner for modes with < 40 columns

- Makefile
- bannex/main.s
- bannex/screen_default_color_from_nvram.s
- bannex/sleep_cont.s
- basic/init.s
- basic/x16additions.s
- inc/bannex.inc
This commit has a net savings of 70 bytes in BASIC.
There's more work to be done here but this one was simple.
> [BASIC/BANNEX] move some code from x16additions into annex

- basic/token2.s
- basic/tokens.s
- basic/x16additions.s
- math/math.inc
POINTER returns the pointer to a variable structure, STRPTR returns a value pointing to the first character of a string in memory.
Also there's a random unrelated typo correction in a comment in these commits.
> [BASIC] add POINTER/STRPTR functions

- basic/code13.s
- basic/x16additions.s
Juggled some things around to save some bytes and reuse some existing code.
> [BASIC] make FRE(n) always return a positive value

- Makefile
- bannex/help.s
- bannex/main.s
- basic/token2.s
- basic/tokens.s
- basic/x16additions.s
- inc/bannex.inc
This is a rudimentary HELP command that displays a brief blurb about where the docs are
Non-release build:
Release build:
Closes #64
> [BASIC] new HELP command

- util/control.s
This was a request from Adrian.
> [UTIL] add SMPTE test pattern

- graphics/drivers/framebuffer.s
> [GRAPH] fix off by one error, and logic bug in checking increment 320 mode for accel

- dos/functions.s
This fixes a problem in the current master that prevents file copying to work properly.
The issue may be observed by the following command:
```DOS"C:FILE2=FILE1"```
where FILE1 already exists on the SD card, and is copied to FILE2. FILE2 is currently created, but the contents is scrambled.
I found two issues in the current code causing this:
- The first issue was that the function fat32_read was called in the function copy_do (file: dos/functions.s) with bit 7 of krn_ptr1 set. This caused all received data to be stored to the same destination address. The copy function expected fat32_read to store the data to a 256 byte buffer, which requires bit 7 to be cleared.
- When the buffer is in banked ram, fat32_read will use the buffer stored in variable bank_save. This was always bank 1 but the …
> Fix for fat32 bug preventing file copy to work properly

- basic/x16additions.s
> Fix to prevent OLD to load autoboot.x16

- basic/code17.s
Closes #82 
Thanks for your patience
> [BASIC] allow VAL() to parse hex/binary literals

- LICENSE.md
Missed this on the previous update which removed GEOS.
> [META] update LICENSE

- kernal/drivers/x16/clock.s
- kernal/drivers/x16/rtc.s
> feat: have clock_get_date_time return day of week in r3H

- Makefile
- bannex/main.s
- bannex/tile.s
- basic/token2.s
- basic/tokens.s
- basic/x16additions.s
- inc/bannex.inc
> [BASIC/BANNEX] add TILE command to BASIC

- Makefile
> [BUILD] Makefile dependency fixes and enhancements

- basic/x16additions.s
BANK 2-3 is for IO3 ($9F60-$9F7F)
BANK 4-5 is for IO4 ($9F80-$9F9F)
> [BASIC] allow VPOKE/VPEEK to reach addon VERA cards with bank >= 2

- Makefile
- bannex/basic_far.s
- bannex/sprite.s
friendlier for moving sprites partially offscreen to the left and top
> [BANNEX] allow MOVSPR's x/y to be negative

- util/control.s
> [UTIL] clear 240p flag when changing vertical scaling

- fat32/fat32.s
> [FAT32] fix problematic rename across directories

- kernal/cbm/channel/close.s
> [KERNAL] properly handle close of device 1

- audio/fm.s
> [AUDIO] fix wrong-bank read bug, avoid reading uninitialized memory

- Makefile
- bannex/basic_far.s
- bannex/main.s
- bannex/tile.s
- basic/token2.s
- basic/tokens.s
- basic/x16additions.s
- inc/bannex.inc
This PR should solve the request from https://github.com/X16Community/x16-rom/issues/271
> Created TILAT & ATTR functions

- util/menu.s
Let me know if the warning should be done in a different way
> Added ability to launch diagnostic bank from MENU

- kernal/drivers/x16/ps2mouse.s
- kernal/x16/extapi.s
> [KERNAL] extapi: add mouse_sprite_offset

- Makefile
Closes #164 
x16-edit and basload will be addressed in #259
> [BUILD] symbolize all internal banks, relist all internal code banks

- kernal/cbm/editor.s
- kernal/x16/extapi.s
> [KERNAL] extapi to change blinking cursor char

- .github/workflows/build.yml
- kernal/drivers/x16/ps2kbd.s
> [KERNAL] fix broken keymap selection logic

- dos/cmdch.s
- dos/declare.s
- dos/file.s
- dos/functions.inc
- dos/functions.s
- dos/parser.s
- fat32/fat32.s
- fat32/main.s
- inc/fat32.inc
> [DOS/FAT32] add T tell command, include position and size of open file channel

- kernal/drivers/x16/ps2data.s
- kernal/drivers/x16/ps2kbd.s
- kernal/x16/extapi.s
also adding extapi to fetch or set kbd LEDs directly
> [KERNAL] enable control and persisting of ps2kbd LED state, respond to numlock

- kernal/drivers/x16/memory.s
This also allows `POKE` to write to BONK RAM.
> [KERNAL] STASH: Add support for writing to a ROM bank

- README.md
- inc/io.inc
see https://cx16forum.com/forum/viewtopic.php?p=34939#p34939
> mode 128 is 320x240

- bannex/basic_far.s
- bannex/hbload.s
- bannex/splash.s
- basic/token2.s
- inc/machine.inc
- kernal/cbm/channel/x16additions.s
- kernal/cbm/init.s
- kernal/drivers/x16/x16.s
- kernal/x16/65c816/extapi16.s
- kernal/x16/extapi.s
and add extapi hooks into these routines
> [KERNAL] change machine type byte to a machine capability/property query
